language: ruby
sudo: required
services:
  - postgresql
before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh
script:
  - bundle install --without production test
  - rake generate_secret_token
  - heroku auth:token
  - heroku run rake db:migrate --app dli-redmine
  - heroku run rake redmine:load_default_data --app dli-redmine
deploy: &heroku
  provider: heroku
  app: dli-redmine
  api_key: $HEROKU_API_KEY